### ISSUE TITLE
Cannot create a project with Light account

### ISSUE THREAD

**Issue by mlyashev** [DaleStewart/Actions_Education#1]
@DaleStewart - I am following Video Step 5: Setting up Backend Service in Your Learning "IBM Client Engineering Self-Paced Customer Care Workshop for Watson Assistant (2023)" and cannot create Project in Code Engine with Light account. Could you please advise how go around this without upgrade to Pay go. Thank you

**Comment by DaleStewart** [comment]
Hello, I am looking into this. I can confirm that a free tier exists, however for some unknown reason free tier accounts can't access it. I am looking for a workaround, but until then, just do your best to follow other non backend steps with your assistant. Sorry for this oversight

**Comment by DaleStewart** [comment]
There will be updated instructions sent out.
